[build]
  base = "frontend"
  command = "yarn install --immutable=false && yarn build"
  publish = "dist"

[build.environment]
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  YARN_NODE_LINKER = "node-modules"
  NODE_OPTIONS = "--max-old-space-size=4096"
